management:
  endpoints:
    enabled-by-default: false # default 사용하지 않을 것
    jmx: # JMX 형태 사용 불가 처리
      exposure:
        exclude: '*'
    web:
      # Actuator 경로 변경
      base-path: /test-actuator
      # 노출 endpoint 추가
      exposure:
        include: metrics, prometheus
  # 개별로 endpoint 추가
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  # actuator 포트 변경
  server:
    port: ${MANAGEMENT_PORT:7463}